# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MyUI(object):
    def setupUi(self, MyUI):
        MyUI.setObjectName("MyUI")
        MyUI.resize(496, 172)
        self.centralwidget = QtWidgets.QWidget(MyUI)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 241, 81))
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(290, 20, 161, 81))
        self.toolButton.setObjectName("toolButton")
        MyUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 23))
        self.menubar.setObjectName("menubar")
        MyUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MyUI)
        self.statusbar.setObjectName("statusbar")
        MyUI.setStatusBar(self.statusbar)

        self.retranslateUi(MyUI)
        self.pushButton.clicked.connect(MyUI.close)
        QtCore.QMetaObject.connectSlotsByName(MyUI)

    def retranslateUi(self, MyUI):
        _translate = QtCore.QCoreApplication.translate
        MyUI.setWindowTitle(_translate("MyUI", "MyFirstUi"))
        self.pushButton.setText(_translate("MyUI", "关闭"))
        self.toolButton.setText(_translate("MyUI", "..."))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MyUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())